<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <WebView2LoaderPreference>Dynamic</WebView2LoaderPreference>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <StartupObject>EmojiManager.App</StartupObject>
    <AssemblyName>EmojiManager</AssemblyName>
    <RootNamespace>EmojiManager</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>
    <AssemblyVersion>1.2.5</AssemblyVersion>
    <FileVersion>1.2.5</FileVersion>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeAllContentForSelfExtract>false</IncludeAllContentForSelfExtract>
    <PublishDocumentationFiles>false</PublishDocumentationFiles>
    <PublishReferencesDocumentationFiles>false</PublishReferencesDocumentationFiles>
    <WebView2NeverCopyLoaderDllToOutputDirectory>true</WebView2NeverCopyLoaderDllToOutputDirectory>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3351.48" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.6" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="EmojiManager.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
